code organised into packages. Modifiers changed.

diff --git a/tests/vpl_execution b/tests/vpl_execution
--- a/tests/vpl_execution
+++ b/tests/vpl_execution
@@ -1,38 +1,34 @@
 #! /bin/bash
 
-cat > vpl_execution <<EEOOFF
-#! /bin/bash
-
 
 # ---------- PROGRAMS TESTED (WITHOUT EXTENSION) ---------
 compiled=true
-prog1=DNA
-prog2=Sequence
+prog1=app
+prog2=libr
 # --------------------- STARTING GRADE -------------------
 grade=0
 
 
 # --------------------- GLOBAL VARIABLES -------------------
-declare -a RegexList1=(".*public\s\+static\s\+void\s\+main\s*(.*).*" )
-declare -a Comment1=("a main method" )
-declare -a RegexList2=(".*public\s\+boolean\s\+compareSequence\s*(.*).*" )
-declare -a Comment2=("a compare sequence method" )
+declare -a RegexList1=(".*def\s\+main\s*(.*).*" ".*print\s*(.*).*" )
+declare -a Comment1=("a main function" "a print call" )
+declare -a RegexList2=(".*class\s\+Person.*" ".*def\s\+__init__\s*(.*).*" )
+declare -a Comment2=("a Person class" "a constructor" )
 
 # --------------------- SETTING VALUES FOR GRADES -------------------
-numberOfRegex=\${#RegexList1[*]}+\${#RegexList2[*]}
-compileGrade=10
-regexGrade=30
+numberOfRegex=${#RegexList1[*]}+${#RegexList2[*]}
+compileGrade=30
+regexGrade=40
 numberOfTestCases=4
-testCasesGrade=60
+testCasesGrade=40
 regex=regexGrade/numberOfRegex
 testCase=testCasesGrade/numberOfTestCases
 
 # ----------------- COMPILE STUDENT PROG  ----------------
-javac DNA.java Sequence.java  &> grepLines.out
 
 
 #--- if error, assign a mi&imal grade ---
-if ((\$? > 0)); then
+if (($? > 0)); then
      echo "------------------------"
      echo "Your program has compiler Errors. Please fix these Errors."
      cat grepLines.out
@@ -40,43 +36,43 @@ if ((\$? > 0)); then
      compiled=false
 fi
 
-if grep -q '.*' \${prog1}.java
+if grep -q '.*' ${prog1}.py
 then
-    if [ \${compiled} = true ] ; then
-        grade=\$((grade+compileGrade))
+    if [ ${compiled} = true ] ; then
+        grade=$((grade+compileGrade))
     fi
 fi
 
 
 # ----------- Remove single line comments from code -------------
-sed -i 's|//.*||g' \${prog1}.java
-sed -i 's|//.*||g' \${prog2}.java
+sed -i 's|#.*||g' ${prog1}.py
+sed -i 's|#.*||g' ${prog2}.py
 
 # ----------- TEST THE CODE FOR PARTICULAR PATTERNS -------------
 
 # ----------- TEST Code -------------
 c=0
-for reg in \${RegexList1[*]}; do
-    if grep -q \$reg \${prog1}.java
+for reg in ${RegexList1[*]}; do
+    if grep -q $reg ${prog1}.py
     then
-        tempRegExGrade=\$((tempRegExGrade+regex))
-        grade=\$((grade+regex))
+        tempRegExGrade=$((tempRegExGrade+regex))
+        grade=$((grade+regex))
     else
         echo "------------------------"
-        echo "You have not \${Comment1[\$c]} in" \${prog1}.java
+        echo "You have not ${Comment1[$c]} in" ${prog1}.py
     fi
     ((c++))
 done
 
 c=0
-for reg in \${RegexList2[*]}; do
-    if grep -q \$reg \${prog2}.java
+for reg in ${RegexList2[*]}; do
+    if grep -q $reg ${prog2}.py
     then
-        tempRegExGrade=\$((tempRegExGrade+regex))
-        grade=\$((grade+regex))
+        tempRegExGrade=$((tempRegExGrade+regex))
+        grade=$((grade+regex))
     else
         echo "------------------------"
-        echo "You have not \${Comment2[\$c]} in" \${prog2}.java
+        echo "You have not ${Comment2[$c]} in" ${prog2}.py
     fi
     ((c++))
 done
@@ -84,56 +80,48 @@ done
 
 # --- create test input files ---
 cat > data1.txt <<EOF
-johndoe
-johndoe
-johnnoe
+syed
 EOF
 cat > data2.txt <<EOF
-syed
-abcd
-efgh
+mule
 EOF
 cat > data3.txt <<EOF
-jajja
-hajja
-iaiia
+john
 EOF
 cat > data4.txt <<EOF
-test
-tae0
-1est
+water
 EOF
 
 
 #--- create expected outputs, one for each input file above ---
 cat > data1.out <<EOF
-No Mutation detected!
+Name = syed.
 EOF
 cat > data2.out <<EOF
-Mutation detected!
+Name = mule.
 EOF
 cat > data3.out <<EOF
-Mutation detected!
+Name = john.
 EOF
 cat > data4.out <<EOF
-No Mutation detected!
+Name = water.
 EOF
 
 count=0
-if [ \${compiled} = true ] ; then
+if [ ${compiled} = true ] ; then
     #---loops through the amount of test cases you specified at the top ---
-    for((i=1;i<=\$numberOfTestCases;i++))
+    for((i=1;i<=$numberOfTestCases;i++))
     do
-       java DNA < data\${i}.txt &> user.out
+       python3 app.py < data${i}.txt &> user.out
 
        #--- compute difference ---
        echo "---------------------"
-       diff -y -w --ignore-all-space user.out data\${i}.out > diff.out
+       diff -y -w --ignore-all-space user.out data${i}.out > diff.out
 
        #--- reject if different ---
-       if ((\$? > 0)); then
+       if (($? > 0)); then
           # Wrong Answer
-          echo "Test Case \${i} Failed"
+          echo "Test Case ${i} Failed"
 
           echo ""
           echo "Your answer:"
@@ -141,18 +129,18 @@ if [ \${compiled} = true ] ; then
 
           echo ""
           echo "Expected answer:"
-          cat data\${i}.out
+          cat data${i}.out
        else
           # Answered Correctly
           echo ""
-          echo "Test Case \${i} Passed"
+          echo "Test Case ${i} Passed"
 
           echo ""
           echo "Your answer:"
           cat user.out
 
           #---adds value to grade based on what % you wanted to give for testcases---
-          grade=\$((grade+testCase))
+          grade=$((grade+testCase))
           ((count++))
        fi
     done
@@ -173,8 +161,5 @@ fi
 
 echo "------------------------"
 echo ""
-echo "Grade :=>> \$grade"
+echo "Grade :=>> $grade"
 
-EEOOFF
-
-chmod +x vpl_execution
